### ISSUE TITLE
Failed to resolve component: h-mermaid

### ISSUE THREAD

**Issue by vincenttouzet** [LiHowe/vuepress-plugin-mermaid#3]
Hi, 

First I xant to thank you for this module make exactly what I need.

I'm using vuepress version 2.0.0-beta.51 and I configure the plugin like this : 

```typescript
// vuepress.config.ts
import {defineUserConfig} from "vuepress";

import MermaidPlugin from 'vuepress-plugin-mermaid-next';

export default defineUserConfig({
    plugins: [
        MermaidPlugin.default()
    ]
});

```

I have the following error when running rendering a page:

```
[Vue warn]: Failed to resolve component: h-mermaid
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Introduction.html> 
  at <AsyncComponentWrapper> 
  at <Content> 
  at <Page key="/guide/introduction.html" > 
  at <BaseTransition mode="out-in" onBeforeEnter=fn<onBeforeEnter> onBeforeLeave=fn<pending>  ... > 
  at <Transition key=1 name="fade-slide-y" mode="out-in"  ... > 
  at <Layout> 
  at <Vuepress onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <VuepressApp> [runtime-core.esm-bundler.js:38:16](http://docs.roadie.local/@fs/srv/app/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js)
```

It looks like the client file is not loaded.

After investigating i see that this plugin uses `clientAppEnhanceFiles` to define the client config file but if I look at the documentation I can only see a [clientConfigFile](https://v2.vuepress.vuejs.org/reference/plugin-api.html#clientconfigfile) option :thinking:

**Comment by LiHowe** [comment]
Oh, The `clientAppEnhanceFiles` is earlier version API of vuepress-next, I'm too busy at work to maintain this plugin, I'll try to update the plugin to fit the latest version API  of vuepress sooner or later(before the end of year).

btw, I'm use `Astro` instead of `vuepress` or `vitepress` now

**Comment by LiHowe** [comment]
I just release a new version 0.1.14, hope to solve your question.
